services:
  n8n:
    build:
      context: .
      dockerfile: n8n/Dockerfile
    container_name: n8n-sahiko
    ports:
      - "5677:5677"
    volumes:
      - ./n8n_data:/home/node/.n8n
    env_file:
      - .env
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge
